rails/dotinstall/taskapp/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :projects do
    resources :tasks, only: [:create, :destroy]
  end

  post '/projects/:project_id/tasks/:id/toggle' => 'tasks#toggle'

  root 'projects#index'
end

rails/dotinstall/taskapp/app/models/project.rb
class Project < ApplicationRecord
    has_many :tasks

    validates :title, 
      presence: { message: "入力して下さい" },
      length: { minimum: 3, message: "短すぎ！"}
end

rails/dotinstall/taskapp/app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project
  validates :title, presence: true
  scope :unfinished, -> {where(done: false)}
end

rails/dotinstall/taskapp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

rails/dotinstall/taskapp/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_action :set_project, only: [:show, :edit, :update, :destroy]

  def index
    @projects = Project.all
  end

  def show
    @project = Project.find(params[:id])
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      redirect_to projects_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @project.update(project_params)
      redirect_to projects_path
    else
      render 'edit'
    end
  end

  def destroy
    @project.destroy
    redirect_to projects_path
  end

  private 
    def project_params
      params[:project].permit(:title)
    end

    def set_project
      @project = Project.find(params[:id])
    end

end

rails/dotinstall/taskapp/app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def create
    @project = Project.find(params[:project_id])
    @task = @project.tasks.create(task_params)
    redirect_to project_path(@project.id)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to project_path(params[:project_id])
  end

  def toggle
    render body: nil
    @task = Task.find(params[:id])
    @task.done = !@task.done
    @task.save
  end

  private
    def task_params
      params[:task].permit(:title)
    end

end

rails/dotinstall/taskapp/app/helpers/projects_helper.rb
module ProjectsHelper
end

rails/dotinstall/taskapp/app/helpers/tasks_helper.rb
module TasksHelper
end

rails/dotinstall/taskapp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Taskapp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= image_tag "logo.png" %>
    <%= yield %>
    <%= link_to "Home", projects_path %>
  </body>
</html>

rails/dotinstall/taskapp/app/views/projects/_form.html.erb
<%= form_for @project do |f| %>
<p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
    <% if @project.errors.any? %>
    <%= @project.errors.messages[:title][0] %>
    <% end %>
</p>
<p>
    <%= f.submit %>
</p>

<% end %>

rails/dotinstall/taskapp/app/views/projects/edit.html.erb
<h1>Edit</h1>

<%= render 'form' %>

rails/dotinstall/taskapp/app/views/projects/index.html.erb
<h1>Project</h1>

<ul>
    <% @projects.each do |project| %>
    <li>
      <%= link_to project.title, project_path(project.id) %>
      (<%= project.tasks.unfinished.count %> / <%= project.tasks.count %>)
      <%= link_to "[Edit]", edit_project_path(project.id) %>
      <%= link_to "[Delete]", project_path(project.id), method: :delete, data: { confirm: "are you sure?" } %>
    </li>
    <% end %>
</ul>
<p><%= link_to "Add New", new_project_path %></p>

rails/dotinstall/taskapp/app/views/projects/new.html.erb
<h1>Add New</h1>

<%= render 'form' %>

rails/dotinstall/taskapp/app/views/projects/show.html.erb
<h1><%= @project.title %></h1>

<ul>
  <% @project.tasks.each do |task| %>
  <li>
    <%= check_box_tag '', '', task.done, {'data-id' => task.id, 'data-project_id' => task.project_id} %>
    <%= task.title  %>
    <%= link_to "[Delete]", project_task_path(task.project_id, task.id), method: :delete, data: { confirm: "are you sure?" } %>
  </li>
  <% end %>
  <li>
    <%= form_for [@project, @project.tasks.build] do |f| %>
    <%= f.text_field :title %>
    <%= f.submit %>
    <% end %>
  </li>  
</ul>

<script>
$(function() {
    $("input[type=checkbox]").click(function() {
        $.post('/projects/'+$(this).data('project_id')+'/tasks/'+$(this).data('id')+'/toggle');
    });
});
</script>